[package]
name = "http_handlers"
version = "0.1.0"
authors = ["jrieck <jackdrieck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
<<<<<<< HEAD
warp = "0.2"
=======
warp = "0.2"
>>>>>>> 8f378dac2bcd0ef5d16e2911d84ff6db8261ad03
